### test de page 404
GET http://localhost:3000/dsfsdfsdf

### Création de liste (il faut penser a sauter une ligne aoprès le header (Content-Type: application/json)
POST http://localhost:3000/lists
Content-Type: application/json

{
  "title": "My List"
}

### Création de liste en erreur
POST http://localhost:3000/lists
Content-Type: application/json

### Création de liste en erreur
POST http://localhost:3000/lists
Content-Type: application/json

{
  "title": ""
}

### Récupération de toutes les listes
GET http://localhost:3000/lists

### Récupération d'une liste en erreur d'analyse
GET http://localhost:3000/lists/12z3


### Récupération d'un liste en erreur 404
GET http://localhost:3000/lists/123

### Récupération d'un liste
GET http://localhost:3000/lists/2

### Suppression d'une liste en erreur d'analyse
DELETE http://localhost:3000/lists/4ert

### Suppression d'une liste en erreur 404
DELETE http://localhost:3000/lists/123

### Suppression d'une liste
DELETE http://localhost:3000/lists/3

### Mise à jour sans données de liste en erreur
PATCH http://localhost:3000/lists/123
Content-Type: application/json

### Mise à jour de liste en erreur
PATCH http://localhost:3000/lists/123
Content-Type: application/json

{
  "title": ""
}

### Mise à jour de liste en erreur
PATCH http://localhost:3000/lists/123
Content-Type: application/json

{
  "title": "My List",
  "position": "n"
}

### Mise à jour de liste en erreur 404
PATCH http://localhost:3000/lists/123
Content-Type: application/json

{
  "title": "My List",
  "position": 1
}

### Mise à jour de liste
PATCH http://localhost:3000/lists/1
Content-Type: application/json

{
  "title": "My List",
  "position": 1
}