# Grâce à l'extansion REST Client de Visual Studio Code, vous pouvez tester les requêtes HTTP directement dans votre éditeur de code.
# url de l'extension: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
GET https://swapi.dev/api/people/2